title: Sarah Jacobson # your name (or website title) here
logo: /images/SarahPhotoRE.jpg # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Senior Undergraduate Student at UMBC
  <br><br>
  B.A. in Geography & Environmental Studies
  Certificate in Geographic Information Systems
  <br><br>
  <a href="https://www.linkedin.com/in/sarah-jacobson-70a38b1b0/">View My LinkedIn Profile</a> 

  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
